controllers:
    resource: ../src/Controller/
    type: attribute

api:
    resource: ../src/Controller/Api
    type: attribute

security_login:
    path: /login
    controller: App\Controller\SecurityController::login

security_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
